# Generated by Django 4.1.2 on 2022-10-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Base',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='title',
            new_name='task',
        ),
    ]
