# Generated by Django 4.1.2 on 2022-10-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0002_rename_todo_base_rename_title_base_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(verbose_name='date of the task')),
            ],
        ),
    ]
