# Generated by Django 4.1.2 on 2022-10-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='date',
        ),
    ]
